
import airlines.information.system.ImportMethodClass;
import java.awt.Desktop;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author [Shreesu Thapa, Avigya Aryal, Mubson Karki] - C13
 */


//This class is used for accessing special features of the system like adding flight, editing flight etc.
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackPanel = new javax.swing.JPanel();
        airlinesISLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        searchFlightLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        loginContentPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginContentHeadingLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        pictureLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileMenuitem = new javax.swing.JMenuItem();
        existingFileMenuitem = new javax.swing.JMenuItem();
        exitMenuitem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blackPanel.setBackground(new java.awt.Color(0, 0, 0));
        blackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        airlinesISLabel.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        airlinesISLabel.setForeground(new java.awt.Color(255, 215, 0));
        airlinesISLabel.setText("Airlines Information System");
        airlinesISLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airlinesISLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                airlinesISLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                airlinesISLabelMouseExited(evt);
            }
        });
        blackPanel.add(airlinesISLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        loginLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("<html> <u> Login </u> <html>");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLabelMouseExited(evt);
            }
        });
        blackPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        searchFlightLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchFlightLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchFlightLabel.setText("<html>\n<u>\nSearch Flight\n</u>\n<html>");
        searchFlightLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFlightLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchFlightLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchFlightLabelMouseExited(evt);
            }
        });
        blackPanel.add(searchFlightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, -1));

        exitLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("<html> <u> Exit </u> <html>");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });
        blackPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, -1));

        loginContentPanel.setBackground(new java.awt.Color(204, 255, 204));
        loginContentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 6, true));
        loginContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        loginContentPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        userNameLabel.setText("User Name");
        loginContentPanel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        userNameField.setToolTipText("");
        loginContentPanel.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 40));

        loginButton.setBackground(new java.awt.Color(204, 255, 204));
        loginButton.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 4, true));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginContentPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, 50));

        loginContentHeadingLabel.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        loginContentHeadingLabel.setText("<html> <u>Login As Staff</u> </html>");
        loginContentPanel.add(loginContentHeadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 340, -1));
        loginContentPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 180, 40));

        blackPanel.add(loginContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 470, 360));

        pictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baHpXzf-high-resolution-aircraft-wallpapers.jpg"))); // NOI18N
        pictureLabel.setOpaque(true);
        blackPanel.add(pictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1100, 550));

        getContentPane().add(blackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        fileMenu.setText("File");

        newFileMenuitem.setText("Open New File");
        newFileMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileMenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(newFileMenuitem);

        existingFileMenuitem.setText("Open Saved File");
        existingFileMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingFileMenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(existingFileMenuitem);

        exitMenuitem.setText("Exit");
        exitMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuitem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuitem.setText("About");
        aboutMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuitemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuitem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void airlinesISLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airlinesISLabelMouseClicked
        dispose();
        try {                                     
            HomePage var = new HomePage();
            var.setVisible(true);
            
            Login var_i = new Login();
            var_i.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_airlinesISLabelMouseClicked

    private void airlinesISLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airlinesISLabelMouseEntered
        airlinesISLabel.setFont(new Font("Times New Roman", Font.BOLD, 38));
    }//GEN-LAST:event_airlinesISLabelMouseEntered

    private void airlinesISLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airlinesISLabelMouseExited
        airlinesISLabel.setFont(new Font("Times New Roman", Font.BOLD, 35));
    }//GEN-LAST:event_airlinesISLabelMouseExited

    private void loginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseEntered
        loginLabel.setFont(new Font("Times New Roman", Font.BOLD, 20));
    }//GEN-LAST:event_loginLabelMouseEntered

    private void loginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseExited
        loginLabel.setFont(new Font("Times New Roman", Font.BOLD, 18));
    }//GEN-LAST:event_loginLabelMouseExited

    private void searchFlightLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFlightLabelMouseEntered
        searchFlightLabel.setFont(new Font("Times New Roman", Font.BOLD, 20));
    }//GEN-LAST:event_searchFlightLabelMouseEntered

    private void searchFlightLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFlightLabelMouseExited
        searchFlightLabel.setFont(new Font("Times New Roman", Font.BOLD, 18));
    }//GEN-LAST:event_searchFlightLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setFont(new Font("Times New Roman", Font.BOLD, 20));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setFont(new Font("Times New Roman", Font.BOLD, 18));
    }//GEN-LAST:event_exitLabelMouseExited

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        dispose();
        Login var = new Login();
        var.setVisible(true);
    }//GEN-LAST:event_loginLabelMouseClicked

    private void searchFlightLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFlightLabelMouseClicked
        try {
            dispose();
            Search var = new Search();
            var.setVisible(true);
        } 
        catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchFlightLabelMouseClicked

    //This methods checks whether the username and password give is registered as staff or not.
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        //Calling loginData() method from ImportMethodClss
        ImportMethodClass a = new ImportMethodClass();
        Hashtable<String, String> dict = a.loginData();
        
        boolean check = false;

        //For loop for iterating over the hashmap
        for(String key: dict.keySet())
        {
            {
                String value = dict.get(key);
                
                if(userNameField.getText().equals(key) && passwordField.getText().equals(value))
                {
                    check = true;
                    break;
                }
            }
        }

        //If the validation is correct, the AddingFlight class is opened.
        if(check == true)
        {
            dispose();
            AddingFlight var = new AddingFlight();
            var.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input. Please try again.");
            userNameField.setText("");
            passwordField.setText("");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void newFileMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileMenuitemActionPerformed
        try {
            HomePage var = new HomePage();
            var.setVisible(true);
        }
        catch (IOException ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newFileMenuitemActionPerformed

    private void existingFileMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingFileMenuitemActionPerformed
        try {
            Search var = new Search();
            var.setVisible(true);
            
            BufferedReader file = new BufferedReader(new FileReader(new File(".\\dataWhileOpenExistingFile.csv")));
            ArrayList<String[]> records = new ArrayList<String[]>();
            
            String line = null;
            int row = 0;
            
            while ((line = file.readLine()) != null) {
                
                if (row == 0) {
                    row++;
                    continue;
                }
                String[] splitted = line.split(",");
                records.add(splitted);
            }
            file.close();

            for(String[] data: records)
            {
                var.tab.addRow(new Object[]{});
                int col = 0;
                
                for(String subData: data)
                {
                    var.searchPageTable.setValueAt(subData, var.tab.getRowCount()-1, col);
                    col++;
                }
            }

        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_existingFileMenuitemActionPerformed

    private void exitMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuitemActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuitemActionPerformed

    private void aboutMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuitemActionPerformed
        try{
            URI link = new URI("https://drive.google.com/file/d/1SiBFresB3Ftddgo9-YTJS3opDCFjYjU5/view?usp=sharing");
            Desktop var = Desktop.getDesktop();
            var.browse(link);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Sorry for trouble! We are having an issue. Please check back later");
        }
    }//GEN-LAST:event_aboutMenuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuitem;
    private javax.swing.JLabel airlinesISLabel;
    private javax.swing.JPanel blackPanel;
    private javax.swing.JMenuItem existingFileMenuitem;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JMenuItem exitMenuitem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginContentHeadingLabel;
    private javax.swing.JPanel loginContentPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newFileMenuitem;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel searchFlightLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
